loc_1 = "screenshot\\loc_1.png"
loc_2 = "screenshot\\loc_2.png"
loc_3 = "screenshot\\loc_3.png"
loc_4 = "screenshot\\loc_4.png"
loc_5 = "screenshot\\loc_5.png"
mirage = "screenshot\\mirage.png"
loc_8 = "screenshot\\loc_8.png"
loc_9 = "screenshot\\loc_9.png"
